export const missionHighlights = {
  mercurio: {
    name: 'BepiColombo', status: 'Em trânsito', type: 'Orbitadores', target: 'Mercúrio', partners: 'ESA + JAXA',
    launch: '20 out. 2018', milestone: 'Inserção orbital prevista: 21 nov. 2026', location: 'Rumo à órbita de Mercúrio',
    objective: 'Estudar a superfície, o interior, a exosfera e a magnetosfera de Mercúrio.',
    sourceUrl: 'https://science.nasa.gov/mission/bepicolombo/', sourceLabel: 'NASA Science',
    note: 'BepiColombo é formado por dois orbitadores: o Mercury Planetary Orbiter (MPO), da ESA, e o Mercury Magnetospheric Orbiter (MIO), da JAXA.',
    spacecraft: 'MPO + MIO', instruments: '16 instrumentos entre os dois orbitadores',
    overview: 'A missão usa uma longa sequência de sobrevoos gravitacionais para reduzir a energia orbital antes da captura por Mercúrio.',
    science: ['Composição e geologia da superfície', 'Estrutura interna e campo gravitacional', 'Exosfera e ambiente magnético', 'História e evolução de Mercúrio'],
    highlights: ['Primeira missão da ESA a Mercúrio', 'Primeira missão japonesa a Mercúrio', 'MESSENGER e Mariner 10 foram os visitantes anteriores', 'Seis sobrevoos de Mercúrio estão previstos durante a fase de cruzeiro'],
    timeline: ['2018 · lançamento', '2021 · primeiro sobrevoo de Mercúrio', '2024–2025 · sobrevoos adicionais', '2026 · inserção orbital prevista'],
    imageUrl: 'https://www.esa.int/var/esa/storage/images/esa_multimedia/images/2021/10/bepicolombo_meets_mercury/23493061-1-eng-GB/BepiColombo_meets_Mercury_pillars.png',
    imageCredit: 'ESA/BepiColombo/MTM',
    gallery: [
      { src: 'https://www.esa.int/var/esa/storage/images/esa_multimedia/images/2021/10/bepicolombo_meets_mercury/23493061-1-eng-GB/BepiColombo_meets_Mercury_pillars.png', alt: 'Mercúrio visto pela BepiColombo durante um sobrevoo', credit: 'ESA/BepiColombo/MTM', kind: 'photo' },
      { src: 'https://www.esa.int/var/esa/storage/images/esa_multimedia/images/2025/01/best_images_from_bepicolombo_s_sixth_mercury_flyby/26527094-1-eng-GB/Best_images_from_BepiColombo_s_sixth_Mercury_flyby_pillars.jpg', alt: 'Imagens do sexto sobrevoo de Mercúrio pela BepiColombo', credit: 'ESA/BepiColombo/MTM', kind: 'photo' },
      { src: 'https://assets.science.nasa.gov/dynamicimage/assets/science/psd/photojournal/pia/pia11/pia11406/PIA11406.jpg?crop=faces%2Cfocalpoint&fit=clip&h=486&w=720', alt: 'Mercúrio em composição de cores obtida pela MESSENGER', credit: 'NASA/Johns Hopkins APL/Carnegie Institution of Washington', kind: 'photo' },
    ],
  },
  venus: {
    name: 'DAVINCI', status: 'Em desenvolvimento', type: 'Orbitador + sonda de descida', target: 'Vênus', partners: 'NASA',
    launch: 'Futura', milestone: 'Missão em desenvolvimento', location: 'Atmosfera e superfície de Vênus',
    objective: 'Investigar Vênus da alta atmosfera até a superfície, medindo sua composição e evolução.',
    sourceUrl: 'https://science.nasa.gov/mission/davinci/', sourceLabel: 'NASA Science',
    note: 'DAVINCI combina uma espaçonave de sobrevoo com a sonda de descida Descent Sphere, que fará medições durante a queda pela atmosfera.',
    spacecraft: 'Espaçonave + Descent Sphere', instruments: '7 instrumentos científicos',
    overview: 'Durante a missão, a espaçonave fará sobrevoos de Vênus e acompanhará o planeta; cerca de dois anos depois, a sonda descerá pela atmosfera até a superfície.',
    science: ['Composição química da atmosfera', 'Temperatura, pressão e ventos durante a descida', 'Composição da superfície em Alpha Regio', 'Evolução climática e geológica de Vênus'],
    highlights: ['Primeira missão da NASA dedicada a medir Vênus da alta atmosfera à superfície em uma única campanha', 'Sonda fará medições in situ durante a descida', 'Alpha Regio é alvo de imagens e análises de superfície'],
    timeline: ['Planejamento · missão futura', 'Cruzeiro e sobrevoos de Vênus', 'Descida atmosférica da sonda', 'Medições finais próximas à superfície'],
    imageUrl: 'https://assets.science.nasa.gov/dynamicimage/assets/science/psd/photojournal/pia/pia00/pia00478/PIA00478.jpg?crop=faces%2Cfocalpoint&fit=clip&h=1200&w=1200',
    imageCredit: 'NASA/JPL — dados de radar da missão Magellan',
    gallery: [
      { src: 'https://assets.science.nasa.gov/dynamicimage/assets/science/psd/photojournal/pia/pia00/pia00478/PIA00478.jpg?crop=faces%2Cfocalpoint&fit=clip&h=1200&w=1200', alt: 'Mapa real por radar da superfície de Vênus produzido pela Magellan', credit: 'NASA/JPL — Magellan', kind: 'science', caption: 'CONTEXTO CIENTÍFICO · A DAVINCI ainda não visitou Vênus. Esta imagem real mostra a superfície escondida sob as nuvens; a missão investigará a composição da atmosfera e a geologia de Alpha Regio.' },
      { src: 'https://assets.science.nasa.gov/dynamicimage/assets/science/psd/photojournal/pia/pia23/pia23791/PIA23791.jpg?crop=faces%2Cfocalpoint&fit=clip&h=1000&w=1200', alt: 'Vênus envolto por uma camada global de nuvens, fotografado pela Mariner 10', credit: 'NASA/JPL-Caltech', kind: 'science', caption: 'CONTEXTO CIENTÍFICO · A densa atmosfera é um dos principais motivos para estudar Vênus com medições durante a descida.' },
    ],
  },
  terra: {
    name: 'Landsat 9', status: 'Ativa', type: 'Orbiter de observação da Terra', target: 'Terra', partners: 'NASA + USGS',
    launch: '27 set. 2021', milestone: 'Operacional', location: 'Órbita terrestre',
    objective: 'Monitorar mudanças na superfície terrestre com observações ópticas e infravermelhas.',
    sourceUrl: 'https://science.nasa.gov/mission/landsat-9/', sourceLabel: 'NASA Science',
    note: 'Landsat 9 amplia o registro contínuo de observações da superfície terrestre iniciado pelo programa Landsat há mais de cinco décadas.',
    spacecraft: 'Satélite Landsat 9', instruments: 'OLI + TIRS; 11 bandas espectrais',
    overview: 'O satélite observa a Terra em uma órbita quase polar e heliossíncrona, produzindo dados para ciência, agricultura, água, florestas e gestão de desastres.',
    science: ['Cobertura vegetal e agricultura', 'Água e qualidade ambiental', 'Mudanças de uso e cobertura da terra', 'Temperatura da superfície'],
    highlights: ['Resolução temporal nominal de 16 dias', 'Mais de 700 cenas por dia', 'Resolução espacial de até 15 m no pancromático', 'Parceria operacional NASA–USGS'],
    timeline: ['2021 · lançamento', '2021–presente · operação e aquisição de dados', '16 dias · ciclo nominal de repetição'],
    imageUrl: 'https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/images/imagerecords/86000/86257/epicfirstlight_DSC_2015186_lrg.jpg?crop=faces%2Cfocalpoint&fit=clip&h=1200&w=1200',
    imageCredit: 'NASA/NOAA EPIC — imagem contextual da Terra',
    gallery: [
      { src: 'https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/images/imagerecords/86000/86257/epicfirstlight_DSC_2015186_lrg.jpg?crop=faces%2Cfocalpoint&fit=clip&h=1200&w=1200', alt: 'Imagem real do disco terrestre inteiro capturada pela câmera EPIC do DSCOVR', credit: 'NASA/NOAA EPIC', kind: 'science', caption: 'CONTEXTO CIENTÍFICO · O Landsat 9 não fotografa o globo inteiro de uma vez: ele registra cenas detalhadas da superfície para acompanhar vegetação, água, gelo, agricultura e mudanças ambientais.' },
    ],
  },
  marte: {
    name: 'Perseverance', status: 'Ativa', type: 'Rover', target: 'Cratera Jezero', partners: 'NASA',
    launch: '30 jul. 2020', milestone: 'Pouso: 18 fev. 2021', location: 'Marte · Cratera Jezero',
    objective: 'Buscar sinais de vida microbiana antiga e coletar amostras de rocha e regolito para possível retorno à Terra.',
    sourceUrl: 'https://science.nasa.gov/mission/mars-2020-perseverance/', sourceLabel: 'NASA Science',
    note: 'Perseverance estuda a habitabilidade passada de Jezero, coleta amostras e opera com instrumentos destinados a geologia, ambiente e futura exploração humana.',
    spacecraft: 'Rover Perseverance', instruments: 'Conjunto de instrumentos científicos + MOXIE; Ingenuity como demonstração tecnológica',
    overview: 'O rover explora Jezero, investiga rochas e sedimentos e constrói um conjunto de amostras que poderá ser estudado em laboratórios terrestres no futuro.',
    science: ['Habitabilidade passada de Marte', 'Busca por sinais de vida microbiana antiga', 'Geologia e história da água em Jezero', 'Coleta e armazenamento de amostras'],
    highlights: ['MOXIE produziu oxigênio a partir do CO₂ marciano', 'Descobriu e analisou rochas ígneas em Jezero', 'Encontrou evidências de antigos ambientes lacustres', 'O helicóptero Ingenuity realizou 72 voos antes do fim da demonstração'],
    timeline: ['2020 · lançamento', '2021 · pouso em Jezero', '2021–presente · exploração e coleta de amostras'],
    imageUrl: 'https://assets.science.nasa.gov/dynamicimage/assets/science/psd/solar/internal_resources/6093/PIA25681.jpg?crop=faces%2Cfocalpoint&fit=clip&h=1122&w=1200',
    imageCredit: 'NASA/JPL-Caltech/MSSS',
    gallery: [
      { src: 'https://assets.science.nasa.gov/dynamicimage/assets/science/psd/solar/internal_resources/6093/PIA25681.jpg?crop=faces%2Cfocalpoint&fit=clip&h=1122&w=1200', alt: 'Perseverance na Cratera Jezero', credit: 'NASA/JPL-Caltech/MSSS', kind: 'photo' },
      { src: 'https://assets.science.nasa.gov/dynamicimage/assets/science/psd/photojournal/pia/pia24/pia24487/PIA24487.jpg?crop=faces%2Cfocalpoint&fit=clip&h=1920&w=2560', alt: 'Perseverance durante seu primeiro deslocamento em Marte', credit: 'NASA/JPL-Caltech', kind: 'photo' },
    ],
  },
  jupiter: {
    name: 'Europa Clipper', status: 'Em trânsito', type: 'Orbitador / sobrevoos', target: 'Europa · sistema de Júpiter', partners: 'NASA / JPL',
    launch: '14 out. 2024', milestone: 'Chegada a Júpiter: abr. 2030', location: 'A caminho do sistema de Júpiter',
    objective: 'Determinar se Europa possui condições que poderiam sustentar vida e estudar seu oceano, gelo, composição e geologia.',
    sourceUrl: 'https://science.nasa.gov/mission/europa-clipper/', sourceLabel: 'NASA Science',
    note: 'Europa Clipper vai fazer dezenas de sobrevoos próximos de Europa; o plano inclui quase 50 passagens próximas, algumas a apenas 25 km da superfície.',
    spacecraft: 'Orbitador Europa Clipper', instruments: '9 instrumentos científicos',
    overview: 'A missão foi lançada em outubro de 2024 e fará uma investigação detalhada de Europa a partir do sistema joviano.',
    science: ['Estrutura da crosta de gelo', 'Oceano subsuperficial', 'Composição e química de Europa', 'Geologia e potencial habitável'],
    highlights: ['Primeira missão dedicada a uma investigação científica detalhada de Europa', 'Quase 50 sobrevoos próximos planejados', 'Conjunto de 9 instrumentos científicos', 'Pode voar a cerca de 25 km da superfície em passagens selecionadas'],
    timeline: ['2024 · lançamento', '2030 · chegada ao sistema de Júpiter', 'Após chegada · campanha de sobrevoos de Europa'],
    imageUrl: 'https://assets.science.nasa.gov/dynamicimage/assets/science/psd/photojournal/pia/pia19/pia19048/PIA19048.jpg?crop=faces%2Cfocalpoint&fit=clip&h=1200&w=1600',
    imageCredit: 'NASA/JPL-Caltech/SETI Institute — imagens da missão Galileo',
    gallery: [
      { src: 'https://assets.science.nasa.gov/dynamicimage/assets/science/psd/photojournal/pia/pia19/pia19048/PIA19048.jpg?crop=faces%2Cfocalpoint&fit=clip&h=1200&w=1600', alt: 'Imagem em cores naturais aproximadas da superfície gelada de Europa obtida pela missão Galileo', credit: 'NASA/JPL-Caltech/SETI Institute', kind: 'science', caption: 'CONTEXTO CIENTÍFICO · A Europa Clipper ainda está a caminho de Júpiter. As fraturas e regiões alteradas da superfície de Europa ajudam a investigar a possibilidade de um oceano sob o gelo.' },
      { src: 'https://assets.science.nasa.gov/dynamicimage/assets/science/psd/photojournal/pia/pia25/pia25499/PIA25499.jpg?crop=faces%2Cfocalpoint&fit=clip&h=1200&w=1600', alt: 'Detalhes de falhas e regiões lisas na crosta gelada de Europa, registrados pela Galileo', credit: 'NASA/JPL-Caltech', kind: 'science', caption: 'CONTEXTO CIENTÍFICO · A missão vai mapear a crosta, a composição e indícios de atividade relacionados ao possível oceano subterrâneo.' },
    ],
  },
  saturno: {
    name: 'Cassini–Huygens', status: 'Concluída · 1997–2017', type: 'Orbitador + sonda', target: 'Saturno e suas luas', partners: 'NASA + ESA + ASI',
    launch: '15 out. 1997', milestone: 'Fim da missão: 15 set. 2017', location: 'Sistema de Saturno',
    objective: 'Estudar Saturno, seus anéis, sua atmosfera, magnetosfera e luas, incluindo Titã e Encélado.',
    sourceUrl: 'https://science.nasa.gov/mission/cassini/about-the-mission/', sourceLabel: 'NASA Science',
    note: 'Cassini–Huygens combinou um orbitador da NASA com a sonda Huygens da ESA, que pousou em Titã em janeiro de 2005.',
    spacecraft: 'Orbitador Cassini + sonda Huygens', instruments: '12 instrumentos no orbitador',
    overview: 'A missão investigou Saturno e seu sistema por 13 anos em órbita, incluindo a fase Grand Finale, antes de encerrar a missão na atmosfera do planeta.',
    science: ['Atmosfera e estrutura interna de Saturno', 'Estrutura e dinâmica dos anéis', 'Titã e sua química atmosférica', 'Encélado e seu oceano subterrâneo'],
    highlights: ['Descobriu evidências de um oceano global em Encélado', 'Revelou mares e lagos de metano líquido em Titã', 'Realizou 162 sobrevoos direcionados de luas', 'Encerrou a missão no Grand Finale entre o planeta e seus anéis'],
    timeline: ['1997 · lançamento', '2004 · chegada a Saturno', '2005 · pouso da Huygens em Titã', '2016–2017 · Grand Finale', '2017 · encerramento'],
    imageUrl: 'https://assets.science.nasa.gov/dynamicimage/assets/science/psd/photojournal/pia/pia17/pia17218/PIA17218.jpg?crop=faces%2Cfocalpoint&fit=clip&h=2500&w=6000',
    imageCredit: 'NASA/JPL-Caltech/Space Science Institute',
    gallery: [
      { src: 'https://assets.science.nasa.gov/dynamicimage/assets/science/psd/photojournal/pia/pia17/pia17218/PIA17218.jpg?crop=faces%2Cfocalpoint&fit=clip&h=2500&w=6000', alt: 'Saturno e seus anéis vistos pela Cassini', credit: 'NASA/JPL-Caltech/SSI', kind: 'photo' },
      { src: 'https://assets.science.nasa.gov/dynamicimage/assets/science/cds/general/images/pia17474/PIA17474~large.jpg', alt: 'Saturno em vista natural da Cassini', credit: 'NASA/JPL-Caltech/SSI/Cornell', kind: 'photo' },
    ],
  },
  urano: {
    name: 'Voyager 2', status: 'Sobrevoo histórico · 1986', type: 'Sobrevoo planetário', target: 'Urano', partners: 'NASA / JPL',
    launch: '20 ago. 1977', milestone: 'Encontro com Urano: 24 jan. 1986', location: 'Urano',
    objective: 'Realizar o primeiro sobrevoo próximo de Urano e investigar sua atmosfera, magnetosfera, anéis e luas.',
    sourceUrl: 'https://science.nasa.gov/mission/voyager/voyager-2/', sourceLabel: 'NASA Science',
    note: 'Voyager 2 foi a primeira espaçonave a voar por Urano e continua sendo a única a ter estudado o planeta de perto.',
    spacecraft: 'Voyager 2', instruments: '11 instrumentos científicos',
    overview: 'A missão usou assistência gravitacional para alcançar Urano e abriu a exploração de um planeta pouco conhecido antes do encontro.',
    science: ['Atmosfera e ventos', 'Campo magnético e magnetosfera', 'Anéis e luas', 'Estrutura do sistema de Urano'],
    highlights: ['Descobriu 10 novas luas', 'Descobriu dois novos anéis', 'Encontrou um campo magnético inclinado e deslocado', 'Obteve imagens detalhadas das maiores luas'],
    timeline: ['1977 · lançamento', '1986 · encontro com Urano', '2018 · entrada em espaço interestelar'],
    imageUrl: 'https://assets.science.nasa.gov/dynamicimage/assets/science/psd/photojournal/pia/pia18/pia18182/PIA18182.jpg?crop=faces%2Cfocalpoint&fit=clip&h=1720&w=1720',
    imageCredit: 'NASA/JPL-Caltech',
    gallery: [
      { src: 'https://assets.science.nasa.gov/dynamicimage/assets/science/psd/photojournal/pia/pia18/pia18182/PIA18182.jpg?crop=faces%2Cfocalpoint&fit=clip&h=1720&w=1720', alt: 'Urano visto pela Voyager 2', credit: 'NASA/JPL-Caltech', kind: 'photo' },
      { src: 'https://assets.science.nasa.gov/dynamicimage/assets/science/psd/photojournal/pia/pia00/pia00143/PIA00143.jpg?crop=faces%2Cfocalpoint&fit=clip&h=960&w=794', alt: 'Urano em crescente fotografado pela Voyager 2', credit: 'NASA/JPL-Caltech', kind: 'photo' },
      { src: 'https://assets.science.nasa.gov/dynamicimage/assets/science/psd/photojournal/pia/pia01/pia01976/PIA01976.jpg?crop=faces%2Cfocalpoint&fit=clip&h=740&w=740', alt: 'Anéis de Urano e duas luas fotografados pela Voyager 2', credit: 'NASA/JPL', kind: 'photo' },
    ],
  },
  netuno: {
    name: 'Voyager 2', status: 'Sobrevoo histórico · 1989', type: 'Sobrevoo planetário', target: 'Netuno', partners: 'NASA / JPL',
    launch: '20 ago. 1977', milestone: 'Encontro com Netuno: 25 ago. 1989', location: 'Netuno',
    objective: 'Realizar o primeiro e único sobrevoo próximo de Netuno e estudar sua atmosfera, anéis, magnetosfera e luas.',
    sourceUrl: 'https://science.nasa.gov/mission/voyager/voyager-2/', sourceLabel: 'NASA Science',
    note: 'Voyager 2 foi a primeira espaçonave a voar por Netuno e continua sendo a única a ter estudado o planeta de perto.',
    spacecraft: 'Voyager 2', instruments: '11 instrumentos científicos',
    overview: 'O sobrevoo de 1989 fechou a sequência dos quatro planetas gigantes e revelou um mundo mais ativo e complexo do que se imaginava.',
    science: ['Atmosfera e circulação', 'Anéis e magnetosfera', 'Novas luas', 'Dinâmica das grandes tempestades'],
    highlights: ['Descobriu seis novas luas', 'Descobriu quatro novos anéis', 'Revelou ventos de até ~1.100 km/h', 'Identificou a Grande Mancha Escura'],
    timeline: ['1977 · lançamento', '1989 · encontro com Netuno', '2018 · entrada em espaço interestelar'],
    imageUrl: 'https://assets.science.nasa.gov/dynamicimage/assets/science/psd/photojournal/pia/pia00/pia00046/PIA00046.jpg?crop=faces%2Cfocalpoint&fit=clip&h=1000&w=1000',
    imageCredit: 'NASA/JPL',
    gallery: [
      { src: 'https://assets.science.nasa.gov/dynamicimage/assets/science/psd/photojournal/pia/pia00/pia00046/PIA00046.jpg?crop=faces%2Cfocalpoint&fit=clip&h=1000&w=1000', alt: 'Netuno em imagem de disco completo obtida pela Voyager 2', credit: 'NASA/JPL', kind: 'photo' },
      { src: 'https://assets.science.nasa.gov/dynamicimage/assets/science/psd/photojournal/pia/pia01/pia01993/PIA01993.jpg?crop=faces%2Cfocalpoint&fit=clip&h=1000&w=1800', alt: 'Netuno visto pela Voyager 2', credit: 'NASA/JPL', kind: 'photo' },
      { src: 'https://assets.science.nasa.gov/dynamicimage/assets/science/psd/photojournal/pia/pia02/pia02209/PIA02209.jpg?crop=faces%2Cfocalpoint&fit=clip&h=800&w=1009', alt: 'Netuno observado pela Voyager 2 em duas posições sucessivas', credit: 'NASA/JPL', kind: 'photo' },
    ],
  },
};
