export const moonMissionFilters = [
  { id: 'all', label: 'Todas' },
  { id: 'apollo', label: 'Apollo' },
  { id: 'artemis', label: 'Artemis' },
  { id: 'luna', label: 'Luna' },
  { id: 'change', label: "Chang'e" },
  { id: 'chandrayaan', label: 'Chandrayaan' },
  { id: 'other', label: 'Outras' },
];

export const moonMissions = [
  {
    id: 'apollo-11',
    program: 'apollo',
    programLabel: 'Apollo',
    code: 'A11',
    state: 'historical',
    name: 'Apollo 11',
    status: 'Concluída · 1969',
    type: 'Pouso tripulado',
    target: 'Mar da Tranquilidade',
    partners: 'NASA',
    launch: '16 jul. 1969',
    milestone: 'Pouso: 20 jul. 1969',
    location: 'Lua · Mar da Tranquilidade',
    spacecraft: 'Saturn V + Columbia + Eagle',
    instruments: 'Câmera de TV, sismômetro, refletor laser e experimentos de superfície',
    objective: 'Realizar o primeiro pouso tripulado na Lua e retornar à Terra com amostras e dados científicos.',
    overview: 'Apollo 11 cumpriu o primeiro pouso humano na Lua. A missão também instalou experimentos, coletou amostras e registrou observações da superfície lunar.',
    science: ['Amostras de solo e rochas lunares', 'Experimentos sísmicos e de laser ranging', 'Observações da superfície e do ambiente lunar'],
    highlights: ['Primeiro pouso humano na Lua', 'Primeiros seres humanos a caminhar na superfície lunar', 'Amostras e experimentos científicos retornaram à Terra'],
    timeline: ['1969 · lançamento', '1969 · entrada em órbita lunar', '1969 · pouso no Mar da Tranquilidade', '1969 · retorno à Terra'],
    sourceUrl: 'https://www.nasa.gov/mission/apollo-11/',
    sourceLabel: 'NASA',
    imageUrl: 'https://www.nasa.gov/wp-content/uploads/2019/07/edu_srch_celebrate_the_50th_anniversary_apollo11.jpg?w=1024',
    imageCredit: 'NASA',
  },
  {
    id: 'apollo-15',
    program: 'apollo',
    programLabel: 'Apollo',
    code: 'A15',
    state: 'historical',
    name: 'Apollo 15',
    status: 'Concluída · 1971',
    type: 'Pouso tripulado',
    target: 'Hadley–Apennine',
    partners: 'NASA',
    launch: '26 jul. 1971',
    milestone: 'Pouso: 30 jul. 1971',
    location: 'Lua · Hadley–Apennine',
    spacecraft: 'Saturn V + Endeavour + Falcon + Lunar Roving Vehicle',
    instruments: 'Instrumentos de superfície, câmera de mapeamento e experimentos ALSEP',
    objective: 'Explorar geologia lunar com maior mobilidade, conduzir experimentos de superfície e ampliar a ciência em órbita.',
    overview: 'Apollo 15 foi a primeira das missões Apollo de maior duração e mobilidade. O Lunar Roving Vehicle ampliou a área explorada pelos astronautas.',
    science: ['Geologia do Hadley–Apennine', 'Experimentos de superfície e sísmica', 'Observações orbitais e fotografia científica'],
    highlights: ['Primeira missão Apollo com Lunar Roving Vehicle', 'Mais de 17 milhas percorridas com o rover', 'Mais de 170 lb de amostras lunares coletadas'],
    timeline: ['1971 · lançamento', '1971 · chegada à órbita lunar', '1971 · pouso e três EVAs', '1971 · retorno à Terra'],
    sourceUrl: 'https://www.nasa.gov/mission/apollo-15/',
    sourceLabel: 'NASA',
    imageUrl: 'https://www.nasa.gov/wp-content/uploads/2021/07/apollo_15_moon_landing_28_eva3_scott_w_us_flag_as15-88-11863hr.jpg?w=985',
    imageCredit: 'NASA',
    imageKind: 'photo',
    imageAlt: 'Astronauta da Apollo 15 ao lado da bandeira e do módulo lunar na superfície da Lua',
  },
  {
    id: 'artemis-ii',
    program: 'artemis',
    programLabel: 'Artemis',
    code: 'AII',
    state: 'historical',
    name: 'Artemis II',
    status: 'Concluída · 2026',
    type: 'Sobrevoo lunar tripulado',
    target: 'Órbita lunar / sobrevoo',
    partners: 'NASA + CSA',
    launch: '1 abr. 2026',
    milestone: 'Retorno: 10 abr. 2026',
    location: 'Terra → Lua → Terra',
    spacecraft: 'SLS + Orion',
    instruments: 'Sistemas de voo, experimentos científicos e demonstrações de espaço profundo',
    objective: 'Testar com tripulação os principais sistemas de voo espacial profundo da Artemis em uma missão ao redor da Lua.',
    overview: 'Artemis II foi o primeiro voo tripulado do programa Artemis e realizou um sobrevoo da Lua antes de retornar à Terra.',
    science: ['Observações da Lua durante o sobrevoo', 'Teste de sistemas Orion e SLS com tripulação', 'Investigações para apoiar futuras missões humanas'],
    highlights: ['Primeiro voo tripulado da Artemis', 'Primeiro voo tripulado da Orion', 'Voo de cerca de 9 dias ao redor da Lua'],
    timeline: ['2026 · lançamento', '2026 · sobrevoo lunar', '2026 · retorno à Terra'],
    sourceUrl: 'https://www.nasa.gov/mission/artemis-ii/',
    sourceLabel: 'NASA',
    imageUrl: 'https://images-assets.nasa.gov/image/art002e015231/art002e015231~large.jpg?crop=faces%2Cfocalpoint&fit=clip&h=1280&w=1920',
    imageCredit: 'NASA',
  },
  {
    id: 'artemis-iii',
    program: 'artemis',
    programLabel: 'Artemis',
    code: 'AIII',
    state: 'future',
    name: 'Artemis III',
    status: 'Futura · 2027',
    type: 'Demonstração tripulada',
    target: 'Órbita terrestre baixa',
    partners: 'NASA + parceiros comerciais',
    launch: 'Previsto para 2027',
    milestone: 'Demonstração de sistemas: 2027',
    location: 'Órbita terrestre baixa · preparação lunar',
    spacecraft: 'SLS + Orion + sistemas de pouso comercial',
    instruments: 'Sistemas de acoplamento, suporte de vida, comunicações e trajes',
    objective: 'Demonstrar em órbita terrestre as capacidades críticas necessárias para futuras missões tripuladas de pouso na Lua.',
    overview: 'Na arquitetura atual da NASA, Artemis III foi reposicionada como missão de demonstração em órbita terrestre baixa, preparando Artemis IV, prevista como a próxima missão tripulada de pouso lunar.',
    science: ['Demonstração de operações integradas', 'Teste de acoplamento com sistemas de pouso comercial', 'Validação de tecnologias para futuras operações lunares'],
    highlights: ['Prevista para 2027', 'Quatro tripulantes', 'Foco atual em reduzir riscos antes do próximo pouso tripulado lunar'],
    timeline: ['2026 · desenvolvimento', '2027 · lançamento planejado', '2027 · demonstrações em órbita terrestre'],
    sourceUrl: 'https://www.nasa.gov/mission/artemis-iii/',
    sourceLabel: 'NASA',
    imageUrl: 'https://images-assets.nasa.gov/image/art002e023575/art002e023575~large.jpg',
    imageCredit: 'NASA — fotografia da Terra feita pela tripulação da Artemis II',
    imageKind: 'photo',
    imageAlt: 'Terra fotografada pela tripulação da Orion durante a Artemis II; imagem contextual, não uma imagem da Artemis III',
    note: 'Contexto visual: esta é uma fotografia real da Terra obtida durante a Artemis II. A Artemis III está planejada para testar operações de encontro e acoplamento em órbita terrestre baixa, não para pousar na Lua.',
  },
  {
    id: 'luna-9',
    program: 'luna',
    programLabel: 'Luna',
    code: 'L9',
    state: 'historical',
    name: 'Luna 9',
    status: 'Concluída · 1966',
    type: 'Aterrissador robótico',
    target: 'Oceanus Procellarum',
    partners: 'URSS',
    launch: '31 jan. 1966',
    milestone: 'Pouso: 3 fev. 1966',
    location: 'Lua · Oceanus Procellarum',
    spacecraft: 'Luna 9',
    instruments: 'Câmeras panorâmicas e instrumentos de superfície',
    objective: 'Demonstrar um pouso suave na Lua e transmitir imagens diretamente da superfície.',
    overview: 'Luna 9 realizou o primeiro pouso suave e sobrevivente na superfície lunar e transmitiu as primeiras imagens panorâmicas obtidas diretamente do solo.',
    science: ['Composição e propriedades do terreno', 'Observação direta da superfície', 'Avaliação do ambiente após o pouso'],
    highlights: ['Primeiro pouso suave bem-sucedido na Lua', 'Primeiras fotografias panorâmicas da superfície lunar'],
    timeline: ['1966 · lançamento', '1966 · pouso na Lua', '1966 · transmissão das imagens'],
    sourceUrl: 'https://science.nasa.gov/resource/first-photo-from-the-surface-of-the-moon-2/',
    sourceLabel: 'NASA Science',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/0a/Luna-9_Space_Probe_Descent_Capsule.jpg',
    imageCredit: 'Wikimedia Commons',
    imageKind: 'replica',
    imageAlt: 'Réplica da cápsula de pouso da Luna 9 em exposição',
  },
  {
    id: 'luna-24',
    program: 'luna',
    programLabel: 'Luna',
    code: 'L24',
    state: 'historical',
    name: 'Luna 24',
    status: 'Concluída · 1976',
    type: 'Amostragem e retorno',
    target: 'Mare Crisium',
    partners: 'URSS',
    launch: '9 ago. 1976',
    milestone: 'Retorno de amostras: 22 ago. 1976',
    location: 'Lua · Mare Crisium',
    spacecraft: 'Luna 24',
    instruments: 'Sistema de perfuração, câmeras e detectores científicos',
    objective: 'Coletar material lunar em profundidade e devolvê-lo à Terra para análise.',
    overview: 'Luna 24 foi uma missão soviética de retorno de amostras que perfurou o regolito no Mare Crisium e trouxe material lunar de volta à Terra.',
    science: ['Amostras de regolito', 'Estrutura vertical do solo lunar', 'Análises de composição e propriedades do material'],
    highlights: ['Retorno automatizado de amostras da Lua', 'Amostras obtidas no Mare Crisium'],
    timeline: ['1976 · lançamento', '1976 · pouso lunar', '1976 · coleta e decolagem', '1976 · retorno à Terra'],
    sourceUrl: 'https://www.nasa.gov/wp-content/uploads/2018/09/beyond-earth-tagged.pdf',
    sourceLabel: 'NASA · Beyond Earth',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/21/Luna24-model-01.jpg',
    imageCredit: 'Svobodat / Wikimedia Commons · CC BY-SA 4.0',
    imageKind: 'replica',
    imageAlt: 'Modelo da espaçonave soviética Luna 24 em exposição',
  },
  {
    id: 'change-4',
    program: 'change',
    programLabel: "Chang'e",
    code: 'CE4',
    state: 'historical',
    name: "Chang'e 4",
    status: 'Concluída · 2019',
    type: 'Aterrissador + rover',
    target: 'Face oculta da Lua',
    partners: 'CNSA',
    launch: '8 dez. 2018',
    milestone: 'Pouso: 3 jan. 2019',
    location: 'Lua · Cratera Von Kármán',
    spacecraft: "Chang'e 4 + Yutu-2",
    instruments: 'Câmeras, espectrômetros, instrumentos de partículas e experimento de radioastronomia',
    objective: 'Realizar o primeiro pouso suave no lado oculto da Lua e estudar sua superfície e ambiente.',
    overview: "Chang'e 4 pousou na cratera Von Kármán, no lado oculto da Lua, usando o satélite retransmissor Queqiao para comunicação com a Terra.",
    science: ['Geologia da Bacia Aitken', 'Ambiente de superfície e subsuperfície', 'Radioastronomia de baixa frequência', 'Interação do vento solar com a superfície'],
    highlights: ['Primeiro pouso suave no lado oculto da Lua', 'Rover Yutu-2 explorou a superfície', 'Uso do satélite Queqiao como retransmissor'],
    timeline: ['2018 · lançamento', '2019 · pouso no lado oculto', '2019–posterior · operações e ciência'],
    sourceUrl: 'https://www.cnsa.gov.cn/english/n6465719/c6805106/content.html',
    sourceLabel: 'CNSA',
    imageUrl: 'https://www.cnsa.gov.cn/n6758823/n6758844/n6760026/n6760035/c6805084/part/6780055.jpg',
    imageCredit: 'CNSA',
    imageKind: 'photo',
    imageAlt: "Imagem do rover Yutu-2 da missão Chang'e 4 na face oculta da Lua",
  },
  {
    id: 'change-6',
    program: 'change',
    programLabel: "Chang'e",
    code: 'CE6',
    state: 'historical',
    name: "Chang'e 6",
    status: 'Concluída · 2024',
    type: 'Amostragem e retorno',
    target: 'Face oculta da Lua · Bacia Aitken',
    partners: 'CNSA',
    launch: '3 mai. 2024',
    milestone: 'Amostras entregues: 25 jun. 2024',
    location: 'Lua · Bacia do Polo Sul–Aitken',
    spacecraft: "Chang'e 6",
    instruments: 'Orbitador, aterrissador, ascensor, retorno e instrumentos de amostragem',
    objective: 'Coletar amostras do lado oculto da Lua e devolvê-las à Terra para estudo.',
    overview: "Chang'e 6 realizou a primeira coleta e retorno de amostras do lado oculto da Lua, obtendo material da Bacia do Polo Sul–Aitken.",
    science: ['Geologia da Bacia do Polo Sul–Aitken', 'Composição do material do lado oculto', 'História geológica da Lua'],
    highlights: ['Primeiro retorno de amostras do lado oculto da Lua', '1.935,3 g de amostras reportadas pela CNSA', 'Missão com orbitador, aterrissador, ascensor e cápsula de retorno'],
    timeline: ['2024 · lançamento', '2024 · pouso e coleta no lado oculto', '2024 · ascensão com amostras', '2024 · retorno à Terra'],
    sourceUrl: 'https://www.cnsa.gov.cn/english/n6465652/n6465653/c10573149/content.html',
    sourceLabel: 'CNSA',
    imageUrl: 'https://www.cnsa.gov.cn/english/n6465652/n6465653/c10541840/part/10541845.jpg',
    imageCredit: 'CNSA / Xinhua',
    imageKind: 'photo',
    imageAlt: "Imagem do conjunto aterrissador-ascensor da Chang'e 6 durante a descida para a Lua",
  },
  {
    id: 'chandrayaan-3',
    program: 'chandrayaan',
    programLabel: 'Chandrayaan',
    code: 'C3',
    state: 'historical',
    name: 'Chandrayaan-3',
    status: 'Concluída · 2023',
    type: 'Aterrissador + rover',
    target: 'Região polar sul',
    partners: 'ISRO',
    launch: '14 jul. 2023',
    milestone: 'Pouso: 23 ago. 2023',
    location: 'Lua · região próxima ao polo sul',
    spacecraft: 'Vikram + Pragyan',
    instruments: 'ChaSTE, ILSA, LP, APXS e LIBS',
    objective: 'Demonstrar pouso suave e mobilidade na superfície lunar, além de realizar medições científicas locais.',
    overview: 'Chandrayaan-3 demonstrou a capacidade de pouso e mobilidade lunar da Índia e realizou experimentos científicos com o módulo Vikram e o rover Pragyan.',
    science: ['Propriedades térmicas do regolito', 'Atividade sísmica local', 'Plasma próximo à superfície', 'Composição elementar do solo'],
    highlights: ['Pouso suave na Lua', 'Rover Pragyan operando na superfície', 'Experimentos locais de composição, calor e sismicidade'],
    timeline: ['2023 · lançamento', '2023 · entrada em órbita lunar', '2023 · pouso', '2023 · operações de superfície'],
    sourceUrl: 'https://www.isro.gov.in/Chandrayaan3_Details.html',
    sourceLabel: 'ISRO',
    imageUrl: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fd/Chandrayaan3-landed.jpg/960px-Chandrayaan3-landed.jpg',
    imageCredit: 'ISRO / Wikimedia Commons · GODL-India',
    imageKind: 'photo',
    imageAlt: 'Vikram lander e rover Pragyan da missão Chandrayaan-3',
  },
  {
    id: 'lro',
    program: 'other',
    programLabel: 'Outras',
    code: 'LRO',
    state: 'active',
    name: 'Lunar Reconnaissance Orbiter',
    status: 'Ativa',
    type: 'Orbitador científico',
    target: 'Lua',
    partners: 'NASA',
    launch: '18 jun. 2009',
    milestone: 'Em operação',
    location: 'Órbita lunar',
    spacecraft: 'Lunar Reconnaissance Orbiter',
    instruments: 'LROC, LOLA, Diviner, LEND, LAMP, Mini-RF e CRaTER',
    objective: 'Mapear a Lua em detalhe e apoiar a ciência lunar e a escolha de locais para futuras missões.',
    overview: 'O LRO estuda a Lua de perto desde 2009, mapeando a superfície e medindo características térmicas, composicionais e do ambiente de radiação.',
    science: ['Topografia e morfologia', 'Temperatura e composição', 'Ambiente de radiação', 'Recursos e locais de pouso'],
    highlights: ['Missão orbital lunar de longa duração', 'Dados usados no planejamento de futuras missões', 'Mapeamento de regiões polares e locais de pouso'],
    timeline: ['2009 · lançamento', '2009 · entrada em órbita lunar', '2009–presente · operações científicas'],
    sourceUrl: 'https://science.nasa.gov/mission/lro/',
    sourceLabel: 'NASA Science',
    imageUrl: 'https://science.nasa.gov/wp-content/uploads/2017/11/174593main-lro-rendering.jpg?w=1063',
    imageCredit: 'NASA',
    imageKind: 'concept',
    imageAlt: 'Representação do Lunar Reconnaissance Orbiter em órbita da Lua',
  },
];
